### ISSUE TITLE
我在训练crnn时出现TypeError: can't pickle Environment objects

### ISSUE THREAD

**Issue by jun214384468** [xiaofengShi/CHINESE-OCR#110]
Traceback (most recent call last):
  File "G:/yjh/python_text/CHINESE-OCR-master/train/keras_train/trainbatch.py", line 106, in <module>
    for X, Y in train_loader:
  File "D:\Anaconda3\envs\python_yjh\lib\site-packages\torch\utils\data\dataloader.py", line 193, in __iter__
    return _DataLoaderIter(self)
  File "D:\Anaconda3\envs\python_yjh\lib\site-packages\torch\utils\data\dataloader.py", line 469, in __init__
    w.start()
  File "D:\Anaconda3\envs\python_yjh\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "D:\Anaconda3\envs\python_yjh\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\Anaconda3\envs\python_yjh\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "D:\Anaconda3\envs\python_yjh\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "D:\Anaconda3\envs\python_yjh\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: can't pickle Environment objects

**Comment by wuaibo** [comment]
设置workers = 0即可
