### ISSUE TITLE
ImportError: cannot import name 'cython_nms'

### ISSUE THREAD

**Issue by qingqing625** [xiaofengShi/CHINESE-OCR#131]
D:\Anaconda3\python.exe D:/PycharmProjects/CHINESE-OCR/demo.py
Using TensorFlow backend.
Traceback (most recent call last):
  File "D:/PycharmProjects/CHINESE-OCR/demo.py", line 8, in <module>
    import model
  File "D:\PycharmProjects\CHINESE-OCR\model.py", line 15, in <module>
    from ctpn.text_detect import text_detect
  File "D:\PycharmProjects\CHINESE-OCR\ctpn\text_detect.py", line 3, in <module>
    from .ctpn.detectors import TextDetector
  File "D:\PycharmProjects\CHINESE-OCR\ctpn\ctpn\detectors.py", line 10, in <module>
    from ..lib.fast_rcnn.nms_wrapper import nms
  File "D:\PycharmProjects\CHINESE-OCR\ctpn\lib\__init__.py", line 1, in <module>
    from . import fast_rcnn
  File "D:\PycharmProjects\CHINESE-OCR\ctpn\lib\fast_rcnn\__init__.py", line 2, in <module>
    from . import nms_wrapper
  File "D:\PycharmProjects\CHINESE-OCR\ctpn\lib\fast_rcnn\nms_wrapper.py", line 2, in <module>
    from ..utils.cython_nms import nms as cython_nms
  File "D:\PycharmProjects\CHINESE-OCR\ctpn\lib\utils\__init__.py", line 10, in <module>
    from . import cython_nms
ImportError: cannot import name 'cython_nms'

路径都是对的，也试过把相对路径改为绝对路径，还是无法导入。请问这是什么原因？该怎么修改？求指点

**Comment by xiaokecui** [comment]
你好,我也碰到了这个问题,想问下你解决了吗

**Comment by xiaokecui** [comment]
> D:\Anaconda3\python.exe D:/PycharmProjects/CHINESE-OCR/demo.py
> Using TensorFlow backend.
> Traceback (most recent call last):
> File "D:/PycharmProjects/CHINESE-OCR/demo.py", line 8, in
> import model
> File "D:\PycharmProjects\CHINESE-OCR\model.py", line 15, in
> from ctpn.text_detect import text_detect
> File "D:\PycharmProjects\CHINESE-OCR\ctpn\text_detect.py", line 3, in
> from .ctpn.detectors import TextDetector
> File "D:\PycharmProjects\CHINESE-OCR\ctpn\ctpn\detectors.py", line 10, in
> from ..lib.fast_rcnn.nms_wrapper import nms
> File "D:\PycharmProjects\CHINESE-OCR\ctpn\lib__init__.py", line 1, in
> from . import fast_rcnn
> File "D:\PycharmProjects\CHINESE-OCR\ctpn\lib\fast_rcnn__init__.py", line 2, in
> from . import nms_wrapper
> File "D:\PycharmProjects\CHINESE-OCR\ctpn\lib\fast_rcnn\nms_wrapper.py", line 2, in
> from ..utils.cython_nms import nms as cython_nms
> File "D:\PycharmProjects\CHINESE-OCR\ctpn\lib\utils__init__.py", line 10, in
> from . import cython_nms
> ImportError: cannot import name 'cython_nms'
> 
> 路径都是对的，也试过把相对路径改为绝对路径，还是无法导入。请问这是什么原因？该怎么修改？求指点

你好,我也遇到了这个问题,想问你解决了吗

**Comment by zhuzhengxiong** [comment]
ImportError: cannot import name 'cython_nms'
