### ISSUE TITLE
linux和windows环境都跑不起来

### ISSUE THREAD

**Issue by buzhihuoyefeng** [xiaofengShi/CHINESE-OCR#152]
我是python3+anaconda环境，执行sh setup-python3.sh到最后一步会报错: No such file or directory

**Comment by buzhihuoyefeng** [comment]
执行python3 demo.py的时候报错Traceback (most recent call last):
  File "demo.py", line 8, in <module>
    import model
  File "/home/public/project/gzj/CHINESE-OCR/model.py", line 13, in <module>
    from crnn.crnn import crnnOcr
  File "/home/public/project/gzj/CHINESE-OCR/crnn/crnn.py", line 11, in <module>
    import models.crnn as crnn
  File "./crnn/models/crnn.py", line 4, in <module>
    import utils
ModuleNotFoundError: No module named 'utils'

**Comment by john012343210** [comment]
我也是相同問題   直接把他改成 from . import utils 就好
