### ISSUE TITLE
请教下，win10环境跑demo.py一直跑不起来，怎么回事。。

### ISSUE THREAD

**Issue by lmw0320** [xiaofengShi/CHINESE-OCR#156]
报错信息如下：(折腾好久了，跪求指点）
2020-08-25 16:21:11.287250: E tensorflow/stream_executor/cuda/cuda_dnn.cc:319] Loaded runtime CuDNN library: 7.4.1 but source was compiled with: 7.6.0.  CuDNN library major and minor version needs to match or have higher minor version in case of CuDNN 7.0 or later version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.
Traceback (most recent call last):
  File "d:/python_files/CV/OCR/CHINESE-OCR/demo.py", line 24, in <module>
    img, model='keras', adjust=True, detectAngle=True)
  File "d:\python_files\CV\OCR\CHINESE-OCR\model.py", line 102, in model
    angle = angle_detect(img=np.copy(img))  ##文字朝向检测
  File "d:\python_files\CV\OCR\CHINESE-OCR\angle\predict.py", line 66, in predict
    pred = model.predict(np.array([img]))
  File "C:\Users\AppData\Roaming\Python\Python36\site-packages\keras\engine\training.py", line 1462, in predict
    callbacks=callbacks)
  File "C:\Users\AppData\Roaming\Python\Python36\site-packages\keras\engine\training_arrays.py", line 324, in predict_loop
    batch_outs = f(ins_batch)
  File "C:\Users\AppData\Roaming\Python\Python36\site-packages\tensorflow_core\python\keras\backend.py", line 3476, in __call__    
    run_metadata=self.run_metadata)
  File "C:\Users\AppData\Roaming\Python\Python36\site-packages\tensorflow_core\python\client\session.py", line 1472, in __call__
    run_metadata_ptr)
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[{{node block1_conv1/convolution}}]]
         [[predictions_class/Softmax/_291]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[{{node block1_conv1/convolution}}]]

**Comment by lmw0320** [comment]
@xiaofengShi
