### ISSUE TITLE
代码错误

### ISSUE THREAD

**Issue by haiya512** [xiaofengShi/CHINESE-OCR#16]
ctpn/lib/utils/bbox.py
感觉这整个文件都有问题，难道不是用Python？用的是cython?

**Comment by xwjBupt** [comment]
请问你demo.py跑通了嘛，我也是这个bbox跑不过去

**Comment by 18813055625** [comment]
同样的问题，作者也不解释下。

**Comment by xiaoxiao-chen** [comment]
测试demo.py时，文件存在，为什么出错呢？import不进去
Traceback (most recent call last):
  File "./demo.py", line 8, in <module>
    import model
  File "/home/xiaoxiao/Downloads/CHINESE-OCR-master/model.py", line 13, in <module>
    from crnn.crnn import crnnOcr
  File "/home/xiaoxiao/Downloads/CHINESE-OCR-master/crnn/crnn.py", line 11, in <module>
    import models.crnn as crnn
  File "./crnn/models/crnn.py", line 5, in <module>
    import utils
ModuleNotFoundError: No module named 'utils'

**Comment by xiaoxiao-chen** [comment]
同样的问题，请问解决了吗？
File "/root/CHINESE-OCR/ctpn/lib/utils/__init__.py", line 1, in <module>
    from . import bbox
  File "/root/CHINESE-OCR/ctpn/lib/utils/bbox.py", line 9
    cimport numpy as np
                ^
SyntaxError: invalid syntax

**Comment by CNU105** [comment]
这些，先按照目录下的脚本文件进行安装。然后在ctpn/lib/utils下按照make.sh利用cython对系列pyx文件进行操作即可。

**Comment by dreamPoet** [comment]
请问make.sh是哪个文件么...?

**Comment by dreamPoet** [comment]
running build_ext
Traceback (most recent call last):
  File "setup_cpu.py", line 134, in <module>
    cmdclass={'build_ext': custom_build_ext},
  File "D:\Anaconda3\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "D:\Anaconda3\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "D:\Anaconda3\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "D:\Anaconda3\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "D:\Anaconda3\lib\distutils\command\build_ext.py", line 339, in run
    self.build_extensions()
  File "setup_cpu.py", line 86, in build_extensions
    customize_compiler_for_nvcc(self.compiler)
  File "setup_cpu.py", line 59, in customize_compiler_for_nvcc
    default_compiler_so = self.compiler_so
AttributeError: 'MSVCCompiler' object has no attribute 'compiler_so'

跑make-for-cpu.sh时python setup_cpu.py build_ext --inplace报错

**Comment by piaobuliao** [comment]
@dreamPoet 可以参考在windows下cpu模式是可以的 https://github.com/eragonruan/text-detection-ctpn/issues/73

**Comment by JianqingWeng** [comment]
我是直接把ctpn/lib/utils/bbox.py这个文件删了，感觉没有存在的必要。但是只有运行又有新的错误
  File "demo.py", line 8, in <module>
    import model
  File "/home/dc2-user/dlprojects/chinese_ocr2/model.py", line 15, in <module>
    from ctpn.text_detect import text_detect
  File "/home/dc2-user/dlprojects/chinese_ocr2/ctpn/text_detect.py", line 3, in <module>
    from .ctpn.detectors import TextDetector
  File "/home/dc2-user/dlprojects/chinese_ocr2/ctpn/ctpn/detectors.py", line 10, in <module>
    from ..lib.fast_rcnn.nms_wrapper import nms
  File "/home/dc2-user/dlprojects/chinese_ocr2/ctpn/lib/__init__.py", line 1, in <module>
    from . import fast_rcnn
  File "/home/dc2-user/dlprojects/chinese_ocr2/ctpn/lib/fast_rcnn/__init__.py", line 2, in <module>
    from . import nms_wrapper
  File "/home/dc2-user/dlprojects/chinese_ocr2/ctpn/lib/fast_rcnn/nms_wrapper.py", line 2, in <module>
    from ..utils.cython_nms import nms as cython_nms
  File "/home/dc2-user/dlprojects/chinese_ocr2/ctpn/lib/utils/__init__.py", line 1, in <module>
    from . import bbox
ImportError: cannot import name 'bbox'
醉了。

**Comment by Bingobbb** [comment]
cd ./ ctpn/lib/utils
./make.sh
即可

**Comment by wwj-2017-1117** [comment]
win10下，demo.py跑不通，总是提示cimport numpy as np有问题。

**Comment by jun214384468** [comment]
@dreamPoet 请问这个问题你解决了吗？

**Comment by JamesWang12345** [comment]
vim CHINESE-OCR/ctpn/lib/utils/gpu_nms.pyx , 确实是语法错误 :
```
import numpy as np
cimport numpy as np

cimport

cimport
numpy as np
cimport
import numpy as np

numpy as np
import numpy as np
```

上述代码修改如下:

```
import numpy as np

cimport numpy as np
```

**Comment by haiya512** [comment]
> 请问你demo.py跑通了嘛，我也是这个bbox跑不过去

好久我都忘记了，还是没跑通
楼主刚更新了代码， 我没有尝试，你可以试试

**Comment by Leo9113** [comment]
请问有人解决cimport numpy as np报错这个问题了吗，有的话麻烦告诉我一下，谢谢
