### ISSUE TITLE
请问如何用crnn训练自己的数据集,具体怎么修改参数啊?

### ISSUE THREAD

**Issue by Cony07f5** [xiaofengShi/CHINESE-OCR#25]
__________________________________________________________________________________________________
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/common_shapes.py", line 686, in _call_cpp_shape_fn_impl
    input_tensors_as_shapes, status)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimension 1 in both shapes must be equal, but are 11 and 5531. Shapes are [512,11] and [512,5531]. for 'Assign_36' (op: 'Assign') with input shapes: [512,11], [512,5531].

作者,您好!我训练自己的数据,10个数字加1一个背景类,然后就报这个错误,不知道怎么修改?求解作者.

**Comment by 18813055625** [comment]
你的类别弄混了，5531是原来的，11是你自己的，把所有5532换成11，应该差不多了

**Comment by Cony07f5** [comment]
@18813055625 首先感谢您! 是的,我已经修改了,但是训练的时候loss值非常低,后面还要看看要改哪里才行.如果方便的话,我们加个we-chat一起交流一下,哈哈 vn:pop0fa

**Comment by 18813055625** [comment]
增加训练步数，增加训练样本，其他我也没有什么好办法

**Comment by Sierkinhane** [comment]
训练样本和验证样本要来自同一分布

**Comment by chinesesuperliu** [comment]
@Cony07f5 你好！我也遇到同样的问题，请问在哪里修改参数（5531改成自己的数）? 非常感谢

**Comment by xjdx123** [comment]
@chinesesuperliu 我是直接将keys_keras.py中的字典换成了自己的字典。字典最后需要添加一个空格符号，作为结束符，然后将加载预训练模型部分注释掉了，重新训练，就可以了。
请问：你训练的时候遇到准确率为零的情况了吗？我自己制作的数据集，训练模型有时候为0，而且特别低。
