### ISSUE TITLE
 No module named 'lib.fast_rcnn'

### ISSUE THREAD

**Issue by dreamPoet** [xiaofengShi/CHINESE-OCR#30]
请问这个该如何解决。。？

D:\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Traceback (most recent call last):
  File "demo.py", line 8, in <module>
    import model
  File "D:\git\CHINESE-OCR\model.py", line 15, in <module>
    from ctpn.text_detect import text_detect
  File "D:\git\CHINESE-OCR\ctpn\text_detect.py", line 4, in <module>
    from .ctpn.model import ctpn
  File "D:\git\CHINESE-OCR\ctpn\ctpn\model.py", line 10, in <module>
    from lib.fast_rcnn.config import cfg
ModuleNotFoundError: No module named 'lib.fast_rcnn'

**Comment by tanzf** [comment]
修改CHINESE-OCR-master\ctpn\ctpn\model.py文件，12-14行代码为：
from ..lib.fast_rcnn.config import cfg
from ..lib.networks.factory import get_network
from ..lib.fast_rcnn.test import test_ctpn
我是这样改的，不报错了
