### ISSUE TITLE
TypeError: function takes exactly 5 arguments (1 given)

### ISSUE THREAD

**Issue by little2Rabbit** [xiaofengShi/CHINESE-OCR#33]
训练时候运行crnn_main.py   
Traceback (most recent call last):
  File "crnn_main.py", line 310, in <module>
    cost = trainBatch(crnn, criterion, optimizer)
  File "crnn_main.py", line 257, in trainBatch
    data = train_iter.next()
  File "/root/anaconda3/envs/xiaofengshi-train2.7/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 336, in __next__
    return self._process_next_batch(batch)
  File "/root/anaconda3/envs/xiaofengshi-train2.7/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 357, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
TypeError: function takes exactly 5 arguments (1 given)

**Comment by zhosteven** [comment]
I have meet the same issue.who knows? thanks .

**Comment by zhosteven** [comment]
one reseaon is that if you use docker ,you need to config workers=0.

**Comment by songtaoshi** [comment]
why i have to config the workers to be 0?

**Comment by blair2020** [comment]
一模一样的错误，请问楼主解决了吗

**Comment by blair2020** [comment]
我觉得可能是lmdb，我就改了这个就报这个错误

**Comment by blair2020** [comment]
我解决了，线程数改为0

**Comment by chlg3321** [comment]
modify num_work=0，it works to me. Thanks
