### ISSUE TITLE
Ubuntu运行demo.py失败，求大佬指导

### ISSUE THREAD

**Issue by CS2JOONGKI** [xiaofengShi/CHINESE-OCR#58]
/home/snoopy/anaconda3/envs/chinese-ocr3/bin/python3 /home/snoopy/project/CHINESE-OCR/demo.py
Using TensorFlow backend.
Traceback (most recent call last):
  File "/home/snoopy/project/CHINESE-OCR/demo.py", line 8, in <module>
    import model
  File "/home/snoopy/project/CHINESE-OCR/model.py", line 15, in <module>
    from ctpn.text_detect import text_detect
  File "/home/snoopy/project/CHINESE-OCR/ctpn/text_detect.py", line 3, in <module>
    from .ctpn.detectors import TextDetector
  File "/home/snoopy/project/CHINESE-OCR/ctpn/ctpn/detectors.py", line 10, in <module>
    from ..lib.fast_rcnn.nms_wrapper import nms
  File "/home/snoopy/project/CHINESE-OCR/ctpn/lib/__init__.py", line 1, in <module>
    from . import fast_rcnn
  File "/home/snoopy/project/CHINESE-OCR/ctpn/lib/fast_rcnn/__init__.py", line 2, in <module>
    from . import nms_wrapper
  File "/home/snoopy/project/CHINESE-OCR/ctpn/lib/fast_rcnn/nms_wrapper.py", line 2, in <module>
    from ..utils.cython_nms import nms as cython_nms
  File "/home/snoopy/project/CHINESE-OCR/ctpn/lib/utils/__init__.py", line 1, in <module>
    from . import bbox
  File "/home/snoopy/project/CHINESE-OCR/ctpn/lib/utils/bbox.py", line 9
    cimport numpy as np
                ^
SyntaxError: invalid syntax

Process finished with exit code 1

**Comment by lfgggogo** [comment]
你没有编译吧

**Comment by bailixuance** [comment]
> 你没有编译吧

请问是怎么编译的呢，有参考方式吗，我也遇到了同样的错误，

**Comment by AAAAaron** [comment]
/CHINESE-OCR/ctpn/lib/utils/make.sh或者CHINESE-OCR/ctpn/lib/utils/make-for-cpu.sh，这两个脚本，或者你按照作者说的在一开始运行那个Bash
##GPU环境
sh setup.sh
## CPU环境
sh setup-cpu.sh
##CPU python3环境
sh setup-python3.sh
