### ISSUE TITLE
undefined symbol: _Py_ZeroStruct

### ISSUE THREAD

**Issue by wyfSunflower** [xiaofengShi/CHINESE-OCR#66]
(venv) gml@gml-TM1701:~/Documents/CHINESE-OCR$ python demo.py 
Using TensorFlow backend.
Traceback (most recent call last):
  File "demo.py", line 8, in <module>
    import model
  File "/home/gml/Documents/CHINESE-OCR/model.py", line 15, in <module>
    from ctpn.text_detect import text_detect
  File "/home/gml/Documents/CHINESE-OCR/ctpn/text_detect.py", line 3, in <module>
    from .ctpn.detectors import TextDetector
  File "/home/gml/Documents/CHINESE-OCR/ctpn/ctpn/detectors.py", line 10, in <module>
    from ..lib.fast_rcnn.nms_wrapper import nms
  File "/home/gml/Documents/CHINESE-OCR/ctpn/lib/__init__.py", line 1, in <module>
    from . import fast_rcnn
  File "/home/gml/Documents/CHINESE-OCR/ctpn/lib/fast_rcnn/__init__.py", line 2, in <module>
    from . import nms_wrapper
  File "/home/gml/Documents/CHINESE-OCR/ctpn/lib/fast_rcnn/nms_wrapper.py", line 2, in <module>
    from ..utils.cython_nms import nms as cython_nms
  File "/home/gml/Documents/CHINESE-OCR/ctpn/lib/utils/__init__.py", line 1, in <module>
    from . import bbox
ImportError: /home/gml/Documents/CHINESE-OCR/ctpn/lib/utils/bbox.so: undefined symbol: _Py_ZeroStruct

**Comment by wyfSunflower** [comment]
(conda_p36) gml@gml-TM1701:~/Documents/CHINESE-OCR$ python demo.py 
Using TensorFlow backend.
Traceback (most recent call last):
  File "demo.py", line 8, in <module>
    import model
  File "/home/gml/Documents/CHINESE-OCR/model.py", line 13, in <module>
    from crnn.crnn import crnnOcr
  File "/home/gml/Documents/CHINESE-OCR/crnn/crnn.py", line 11, in <module>
    import models.crnn as crnn
  File "./crnn/models/crnn.py", line 4, in <module>
    import utils
ModuleNotFoundError: No module named 'utils'
