### ISSUE TITLE
training

### ISSUE THREAD

**Issue by leigaoxiang** [xiaofengShi/CHINESE-OCR#72]
i want to train my data without load the my_model_keras.h5 model！but it failed

here is errors：

Traceback (most recent call last):
  File "F:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1322, in _do_call
    return fn(*args)
  File "F:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1307, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "F:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value batch_normalization_1/moving_mean
         [[Node: batch_normalization_1/moving_mean/read = Identity[T=DT_FLOAT, _class=["loc:@batch_normalization_1/AssignMovingAvg"], _device="/job:localhost/replica:0/task:0/device:GPU:0"](batch_normalization_1/moving_mean)]]
         [[Node: ctc/boolean_mask/Reshape/_225 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1207_ctc/boolean_mask/Reshape", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

During handling of the above exception, another exception occurred:

can you help me
thank you！！

**Comment by shelimingming** [comment]
Have you solved this problem?I have the same promblem。
