### ISSUE TITLE
运行要太久了，结果还是报错了。

### ISSUE THREAD

**Issue by zhoujianwen** [xiaofengShi/CHINESE-OCR#73]
```
(crnn_env) zhoujianwen@zhoujianwen-System:~/CHINESE-OCR$ python demo.py 
Using TensorFlow backend.
Tensor("Placeholder:0", shape=(?, ?, ?, 3), dtype=float32)
Tensor("conv5_3/conv5_3:0", shape=(?, ?, ?, 512), dtype=float32)
Tensor("rpn_conv/3x3/rpn_conv/3x3:0", shape=(?, ?, ?, 512), dtype=float32)
Tensor("lstm_o/Reshape_2:0", shape=(?, ?, ?, 512), dtype=float32)
Tensor("lstm_o/Reshape_2:0", shape=(?, ?, ?, 512), dtype=float32)
Tensor("rpn_cls_score/Reshape_1:0", shape=(?, ?, ?, 20), dtype=float32)
Tensor("rpn_cls_prob:0", shape=(?, ?, ?, ?), dtype=float32)
Tensor("Reshape_2:0", shape=(?, ?, ?, 20), dtype=float32)
Tensor("rpn_bbox_pred/Reshape_1:0", shape=(?, ?, ?, 40), dtype=float32)
Tensor("Placeholder_1:0", shape=(?, 3), dtype=float32)
2019-04-12 17:40:27.097819: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2019-04-12 17:40:27.114773: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2019-04-12 17:40:27.114782: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2019-04-12 17:40:27.114786: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2019-04-12 17:40:27.114790: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
2019-04-12 17:40:27.500428: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:893] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-04-12 17:40:27.501804: I tensorflow/core/common_runtime/gpu/gpu_device.cc:955] Found device 0 with properties: 
name: GeForce RTX 2070
major: 7 minor: 5 memoryClockRate (GHz) 1.71
pciBusID 0000:01:00.0
Total memory: 7.76GiB
Free memory: 7.25GiB
2019-04-12 17:40:27.501865: I tensorflow/core/common_runtime/gpu/gpu_device.cc:976] DMA: 0 
2019-04-12 17:40:27.501888: I tensorflow/core/common_runtime/gpu/gpu_device.cc:986] 0:   Y 
2019-04-12 17:40:27.501918: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1045] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce RTX 2070, pci bus id: 0000:01:00.0)
('Tensor_name is : ', 'conv4_3/weights')
('Tensor_name is : ', 'conv5_1/weights')
('Tensor_name is : ', 'conv1_1/biases')
('Tensor_name is : ', 'conv3_2/biases')
('Tensor_name is : ', 'conv2_1/biases')
('Tensor_name is : ', 'conv1_2/biases')
('Tensor_name is : ', 'conv4_1/weights')
('Tensor_name is : ', 'rpn_bbox_pred/weights')
('Tensor_name is : ', 'rpn_cls_score/biases')
('Tensor_name is : ', 'rpn_conv/3x3/biases')
('Tensor_name is : ', 'lstm_o/bidirectional_rnn/bw/lstm_cell/kernel')
('Tensor_name is : ', 'conv1_1/weights')
('Tensor_name is : ', 'lstm_o/bidirectional_rnn/fw/lstm_cell/kernel')
('Tensor_name is : ', 'lstm_o/bidirectional_rnn/fw/lstm_cell/bias')
('Tensor_name is : ', 'conv3_1/biases')
('Tensor_name is : ', 'rpn_conv/3x3/weights')
('Tensor_name is : ', 'conv2_2/biases')
('Tensor_name is : ', 'conv2_1/weights')
('Tensor_name is : ', 'conv5_3/biases')
('Tensor_name is : ', 'rpn_bbox_pred/biases')
('Tensor_name is : ', 'conv5_2/weights')
('Tensor_name is : ', 'conv4_2/biases')
('Tensor_name is : ', 'conv5_3/weights')
('Tensor_name is : ', 'conv3_3/biases')
('Tensor_name is : ', 'rpn_cls_score/weights')
('Tensor_name is : ', 'conv4_2/weights')
('Tensor_name is : ', 'lstm_o/biases')
('Tensor_name is : ', 'conv5_2/biases')
('Tensor_name is : ', 'conv5_1/biases')
('Tensor_name is : ', 'conv4_3/biases')
('Tensor_name is : ', 'conv4_1/biases')
('Tensor_name is : ', 'conv3_2/weights')
('Tensor_name is : ', 'lstm_o/weights')
('Tensor_name is : ', 'conv3_3/weights')
('Tensor_name is : ', 'conv3_1/weights')
('Tensor_name is : ', 'conv1_2/weights')
('Tensor_name is : ', 'lstm_o/bidirectional_rnn/bw/lstm_cell/bias')
('Tensor_name is : ', 'conv2_2/weights')
load vggnet done
2019-04-12 17:42:01.191133: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1045] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce RTX 2070, pci bus id: 0000:01:00.0)
('The angel of this character is:', 0)
Rotate the array of this img!
Traceback (most recent call last):
  File "demo.py", line 21, in <module>
    img, model='keras', adjust=True, detectAngle=True)
  File "/home/zhoujianwen/CHINESE-OCR/model.py", line 118, in model
    result = crnnRec(img, text_recs, model, adjust=adjust)
  File "/home/zhoujianwen/CHINESE-OCR/model.py", line 57, in crnnRec
    sim_pred = ocr(image)
  File "/home/zhoujianwen/CHINESE-OCR/ocr/model.py", line 96, in predict
    y_pred = basemodel.predict(X)
NameError: global name 'basemodel' is not defined
```

我已经将所以路径设置为全局路径，包括这些checkpoints、VOCdevkit2007、VGG_imagenet.npy、my_model_keras.h5、netCRNN_pytorch.pth、modelAngle.h5
是什么原因造成，可否告诉我。

**Comment by zhoujianwen** [comment]
```git diff```

```
(crnn_env) zhoujianwen@zhoujianwen-System:~/CHINESE-OCR$ git diff
diff --git a/angle/predict.py b/angle/predict.py
index d52cab7..63196d0 100644
--- a/angle/predict.py
+++ b/angle/predict.py
@@ -29,7 +29,7 @@ def load():
     model.compile(
         optimizer=sgd, loss='categorical_crossentropy', metrics=['accuracy'])
     model.load_weights(
-        '/Users/xiaofeng/Code/Github/dataset/CHINESE_OCR/angle/modelAngle.h5')
+        '/home/zhoujianwen/CHINESE-OCR/angle/modelAngle.h5')
     return model
 
 
diff --git a/ctpn/ctpn/model.py b/ctpn/ctpn/model.py
index 6843c3d..5687cd4 100644
--- a/ctpn/ctpn/model.py
+++ b/ctpn/ctpn/model.py
@@ -1,3 +1,4 @@
+# coding:utf-8
 import sys
 import os
 
@@ -33,7 +34,7 @@ def load_tf_model():
     saver = tf.train.Saver()
     # sess = tf.Session(config=config)
     sess = tf.Session()
-    ckpt_path = '/Users/xiaofeng/Code/Github/dataset/CHINESE_OCR/ctpn/ctpn/retrain/ckpt'
+    ckpt_path = '/media/zhoujianwen/Data/dataset/ctpn/checkpoints/'
     ckpt = tf.train.get_checkpoint_state(ckpt_path)
     reader = tf.train.NewCheckpointReader(ckpt.model_checkpoint_path)
     var_to_shape_map = reader.get_variable_to_shape_map()
diff --git a/ctpn/ctpn/other.py b/ctpn/ctpn/other.py
index 2c37706..14e063e 100644
--- a/ctpn/ctpn/other.py
+++ b/ctpn/ctpn/other.py
@@ -1,3 +1,4 @@
+# coding:utf-8
 import cv2
 import numpy as np
 from matplotlib import cm
@@ -77,7 +78,7 @@ def draw_boxes(im,
         # cv2.rectangle(im, tuple(box[:2]), tuple(box[2:4]), c,2)
         # cv2.waitKey(0)
         # cv2.imshow('kk', im)
-        cv2.imwrite('/Users/xiaofeng/Code/Github/Chinese-OCR/test/test_result.png',im)
+        cv2.imwrite('/home/zhoujianwen/Chinese-OCR/test/test_result.png',im)
 
     return text_recs, im
 
diff --git a/ctpn/ctpn/train_net.py b/ctpn/ctpn/train_net.py
index 9a46f6b..433a7da 100644
--- a/ctpn/ctpn/train_net.py
+++ b/ctpn/ctpn/train_net.py
@@ -53,6 +53,6 @@ if __name__ == '__main__':
         # pretrained_model=
         # '/Users/xiaofeng/Code/Github/dataset/CHINESE_OCR/ctpn/pretrain/VGG_imagenet.npy',
         # pretrained_model='/home/xiaofeng/data/ctpn/pretrainde_vgg',
-        pretrained_model=None,
+        pretrained_model='/media/zhoujianwen/Data/dataset/ctpn/VGG_imagenet.npy',
         max_iters=180000,
         restore=bool(int(1)))
diff --git a/ctpn/lib/datasets/pascal_voc.py b/ctpn/lib/datasets/pascal_voc.py
index 28e16d8..928d57f 100644
--- a/ctpn/lib/datasets/pascal_voc.py
+++ b/ctpn/lib/datasets/pascal_voc.py
@@ -35,7 +35,7 @@ class pascal_voc(imdb):
             else devkit_path
         # 将数据文件保存在仓库之外的位置
         # self._devkit_path = '/Users/xiaofeng/Code/Github/dataset/CHINESE_OCR/ctpn/VOCdevkit2007'
-        self._devkit_path = '/home/xiaofeng/data/ctpn/VOCdevkit2007'
+        self._devkit_path = '/media/zhoujianwen/Data/dataset/ctpn/VOCdevkit2007'
         # 得到数据集的目录
         self._data_path = os.path.join(self._devkit_path, 'VOC' + self._year)
 
diff --git a/ctpn/lib/fast_rcnn/config.py b/ctpn/lib/fast_rcnn/config.py
index a8c9876..088d3fb 100644
--- a/ctpn/lib/fast_rcnn/config.py
+++ b/ctpn/lib/fast_rcnn/config.py
@@ -1,3 +1,4 @@
+# coding:utf-8
 # --------------------------------------------------------
 # Fast R-CNN
 # Copyright (c) 2015 Microsoft
diff --git a/ctpn/lib/fast_rcnn/train.py b/ctpn/lib/fast_rcnn/train.py
index 12361e1..cdaedf3 100644
--- a/ctpn/lib/fast_rcnn/train.py
+++ b/ctpn/lib/fast_rcnn/train.py
@@ -1,3 +1,4 @@
+# coding:utf-8
 from __future__ import print_function
 
 import os
diff --git a/ctpn/text_detect.py b/ctpn/text_detect.py
index 493ba00..37cbbbd 100644
--- a/ctpn/text_detect.py
+++ b/ctpn/text_detect.py
@@ -1,3 +1,4 @@
+# coding:utf-8
 import numpy as np
 # import tensorflow as tf
 from .ctpn.detectors import TextDetector
diff --git a/demo.py b/demo.py
index 026d961..f882ee0 100644
--- a/demo.py
+++ b/demo.py
@@ -8,10 +8,10 @@ from PIL import Image
 import model
 # ces
 
-paths = glob('./test/*.*')
+paths = glob('/home/zhoujianwen/CHINESE-OCR/test/*.*')
 
 if __name__ == '__main__':
-    im = Image.open("./test/3.png")
+    im = Image.open("/home/zhoujianwen/CHINESE-OCR/test/3.png")
     img = np.array(im.convert('RGB'))
     t = time.time()
     '''
diff --git a/ocr/model.py b/ocr/model.py
index 41c9459..c357809 100644
--- a/ocr/model.py
+++ b/ocr/model.py
@@ -72,7 +72,7 @@ def get_model(height, nclass):
 
 characters = keys_ocr.alphabet[:]
 modelPath = os.path.join(os.getcwd(), "ocr/ocr0.2.h5")
-# modelPath = '/Users/xiaofeng/Code/Github/dataset/CHINESE_OCR/save_model/my_model_keras.h5'
+ #modelPath = '/media/zhoujianwen/Data/dataset/crnn/my_model_keras.h5'
 height = 32
 nclass=len(characters)+1
 if os.path.exists(modelPath):
diff --git a/setup.sh b/setup.sh
index f75e990..cb921fd 100644
--- a/setup.sh
+++ b/setup.sh
@@ -1,8 +1,8 @@
 # conda create -n chinese-ocr python=2.7 pip scipy numpy PIL jupyter##运用conda 创建python环境
 # source activate chinese-ocr
 
-export PATH=/usr/local/cuda-9.0/bin${PATH:+:${PATH}}
-export LD_LIBRARY_PATH=/usr/local/cuda-9.0/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
+#export PATH=/usr/local/cuda-9.0/bin${PATH:+:${PATH}}
+#export LD_LIBRARY_PATH=/usr/local/cuda-9.0/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
 
 pip install easydict -i https://pypi.tuna.tsinghua.edu.cn/simple/ ##选择国内源，速度更快
 pip install keras==2.0.8  -i https://pypi.tuna.tsinghua.edu.cn/simple/  
@@ -13,7 +13,7 @@ pip install  h5py lmdb mahotas -i https://pypi.tuna.tsinghua.edu.cn/simple/
 conda install pytorch=0.1.12 cuda90 torchvision -c soumith
 pip install futures==3.1.1 -i https://pypi.tuna.tsinghua.edu.cn/simple/
 # conda install tensorflow=1.3 tensorflow-gpu=1.3 ##解决cuda报错相关问题
-cd ./ctpn/lib/utils
-sh make.sh
+#cd ./ctpn/lib/utils
+#sh make.sh
 
 
diff --git a/train/keras-train/allinonetrain.py b/train/keras-train/allinonetrain.py
index cb5db70..2dc0808 100644
--- a/train/keras-train/allinonetrain.py
+++ b/train/keras-train/allinonetrain.py
@@ -268,8 +268,8 @@ if __name__ == '__main__':
     model, basemodel = get_model(height=imgH, nclass=nclass)
     import os
 
-    if os.path.exists('/Users/xiaofeng/Code/Github/dataset/CHINESE_OCR/crnn_ocr/pretrain-models/keras.hdf5'):
-        basemodel.load_weights('/Users/xiaofeng/Code/Github/dataset/CHINESE_OCR/crnn_ocr/pretrain-models/keras.hdf5')
+    if os.path.exists('/home/zhoujianwen/CHINESE_OCR/crnn_ocr/pretrain-models/keras.hdf5'):
+        basemodel.load_weights('/home/zhoujianwen/CHINESE_OCR/crnn_ocr/pretrain-models/keras.hdf5')
 
     ##注意此处保存的是model的权重
     checkpointer = ModelCheckpoint(filepath="save_model/model{epoch:02d}-{val_loss:.4f}.hdf5", monitor='val_loss',
diff --git a/train/keras-train/train.py b/train/keras-train/train.py
index 9240f46..fba6f77 100644
--- a/train/keras-train/train.py
+++ b/train/keras-train/train.py
@@ -90,16 +90,16 @@ if __name__ == '__main__':
     import os
 
     if os.path.exists(
-            '/Users/xiaofeng/Code/Github/dataset/CHINESE_OCR/save_model/my_model_keras.h5'
+            '/media/zhoujianwen/Data/dataset/crnn/my_model_keras.h5'
     ):
         basemodel.load_weights(
-            '/Users/xiaofeng/Code/Github/dataset/CHINESE_OCR/save_model/my_model_keras.h5'
+            '/media/zhoujianwen/Data/dataset/crnn/my_model_keras.h5'
         )
 
     ##注意此处保存的是model的权重
     checkpointer = ModelCheckpoint(
         filepath=
-        "/Users/xiaofeng/Code/Github/dataset/CHINESE_OCR/save_model/my_model_keras.h5",
+        "/media/zhoujianwen/Data/dataset/crnn/my_model_keras.h5",
         monitor='val_loss',
         verbose=0,
         save_weights_only=False,
diff --git a/train/keras-train/trainbatch.py b/train/keras-train/trainbatch.py
index 9680bfd..39d19a4 100644
--- a/train/keras-train/trainbatch.py
+++ b/train/keras-train/trainbatch.py
@@ -20,7 +20,7 @@ nclass = len(characters) + 1
 trainroot = '../data/lmdb/train'
 valroot = '../data/lmdb/val'
 # modelPath = '../pretrain-models/keras.hdf5'
-modelPath = '/Users/xiaofeng/Code/Github/dataset/CHINESE_OCR/save_model/my_model_keras.h5'
+modelPath = '/media/zhoujianwen/Data/dataset/crnn/my_model_keras.h5'
 workers = 4
 imgH = 32
 imgW = 256
@@ -35,7 +35,7 @@ LEARNING_RATE = 0.01
 Learning_decay_step = 20000
 PERCEPTION = 0.3
 EPOCH_NUMS = 1000000
-MODEL_PATH = '/Users/xiaofeng/Code/Github/dataset/CHINESE_OCR/save_model'
+MODEL_PATH = '/media/zhoujianwen/Data/dataset/crnn'
 LOG_FILE = 'log.txt'
 SUMMARY_PATH = './log/'
 if not os.path.exists(MODEL_PATH):
diff --git a/train/pytorch-train/crnn_main.py b/train/pytorch-train/crnn_main.py
index 4083326..6a9cff0 100644
--- a/train/pytorch-train/crnn_main.py
+++ b/train/pytorch-train/crnn_main.py
@@ -58,8 +58,7 @@ parser.add_argument(
 parser.add_argument(
     '--crnn',

(crnn_env) zhoujianwen@zhoujianwen-System:~/CHINESE-OCR$ git diff >> ~/diff.txt
(crnn_env) zhoujianwen@zhoujianwen-System:~/CHINESE-OCR$ cat diff.txt
cat: diff.txt: 没有那个文件或目录
(crnn_env) zhoujianwen@zhoujianwen-System:~/CHINESE-OCR$ cat ~/diff.txt
diff --git a/angle/predict.py b/angle/predict.py
index d52cab7..63196d0 100644
--- a/angle/predict.py
+++ b/angle/predict.py
@@ -29,7 +29,7 @@ def load():
     model.compile(
         optimizer=sgd, loss='categorical_crossentropy', metrics=['accuracy'])
     model.load_weights(
-        '/Users/xiaofeng/Code/Github/dataset/CHINESE_OCR/angle/modelAngle.h5')
+        '/home/zhoujianwen/CHINESE-OCR/angle/modelAngle.h5')
     return model
 
 
diff --git a/ctpn/ctpn/model.py b/ctpn/ctpn/model.py
index 6843c3d..5687cd4 100644
--- a/ctpn/ctpn/model.py
+++ b/ctpn/ctpn/model.py
@@ -1,3 +1,4 @@
+# coding:utf-8
 import sys
 import os
 
@@ -33,7 +34,7 @@ def load_tf_model():
     saver = tf.train.Saver()
     # sess = tf.Session(config=config)
     sess = tf.Session()
-    ckpt_path = '/Users/xiaofeng/Code/Github/dataset/CHINESE_OCR/ctpn/ctpn/retrain/ckpt'
+    ckpt_path = '/media/zhoujianwen/Data/dataset/ctpn/checkpoints/'
     ckpt = tf.train.get_checkpoint_state(ckpt_path)
     reader = tf.train.NewCheckpointReader(ckpt.model_checkpoint_path)
     var_to_shape_map = reader.get_variable_to_shape_map()
diff --git a/ctpn/ctpn/other.py b/ctpn/ctpn/other.py
index 2c37706..14e063e 100644
--- a/ctpn/ctpn/other.py
+++ b/ctpn/ctpn/other.py
@@ -1,3 +1,4 @@
+# coding:utf-8
 import cv2
 import numpy as np
 from matplotlib import cm
@@ -77,7 +78,7 @@ def draw_boxes(im,
         # cv2.rectangle(im, tuple(box[:2]), tuple(box[2:4]), c,2)
         # cv2.waitKey(0)
         # cv2.imshow('kk', im)
-        cv2.imwrite('/Users/xiaofeng/Code/Github/Chinese-OCR/test/test_result.png',im)
+        cv2.imwrite('/home/zhoujianwen/Chinese-OCR/test/test_result.png',im)
 
     return text_recs, im
 
diff --git a/ctpn/ctpn/train_net.py b/ctpn/ctpn/train_net.py
index 9a46f6b..433a7da 100644
--- a/ctpn/ctpn/train_net.py
+++ b/ctpn/ctpn/train_net.py
@@ -53,6 +53,6 @@ if __name__ == '__main__':
         # pretrained_model=
         # '/Users/xiaofeng/Code/Github/dataset/CHINESE_OCR/ctpn/pretrain/VGG_imagenet.npy',
         # pretrained_model='/home/xiaofeng/data/ctpn/pretrainde_vgg',
-        pretrained_model=None,
+        pretrained_model='/media/zhoujianwen/Data/dataset/ctpn/VGG_imagenet.npy',
         max_iters=180000,
         restore=bool(int(1)))
diff --git a/ctpn/lib/datasets/pascal_voc.py b/ctpn/lib/datasets/pascal_voc.py
index 28e16d8..928d57f 100644
--- a/ctpn/lib/datasets/pascal_voc.py
+++ b/ctpn/lib/datasets/pascal_voc.py
@@ -35,7 +35,7 @@ class pascal_voc(imdb):
             else devkit_path
         # 将数据文件保存在仓库之外的位置
         # self._devkit_path = '/Users/xiaofeng/Code/Github/dataset/CHINESE_OCR/ctpn/VOCdevkit2007'
-        self._devkit_path = '/home/xiaofeng/data/ctpn/VOCdevkit2007'
+        self._devkit_path = '/media/zhoujianwen/Data/dataset/ctpn/VOCdevkit2007'
         # 得到数据集的目录
         self._data_path = os.path.join(self._devkit_path, 'VOC' + self._year)
 
diff --git a/ctpn/lib/fast_rcnn/config.py b/ctpn/lib/fast_rcnn/config.py
index a8c9876..088d3fb 100644
--- a/ctpn/lib/fast_rcnn/config.py
+++ b/ctpn/lib/fast_rcnn/config.py
@@ -1,3 +1,4 @@
+# coding:utf-8
 # --------------------------------------------------------
 # Fast R-CNN
 # Copyright (c) 2015 Microsoft
diff --git a/ctpn/lib/fast_rcnn/train.py b/ctpn/lib/fast_rcnn/train.py
index 12361e1..cdaedf3 100644
--- a/ctpn/lib/fast_rcnn/train.py
+++ b/ctpn/lib/fast_rcnn/train.py
@@ -1,3 +1,4 @@
+# coding:utf-8
 from __future__ import print_function
 
 import os
diff --git a/ctpn/text_detect.py b/ctpn/text_detect.py
index 493ba00..37cbbbd 100644
--- a/ctpn/text_detect.py
+++ b/ctpn/text_detect.py
@@ -1,3 +1,4 @@
+# coding:utf-8
 import numpy as np
 # import tensorflow as tf
 from .ctpn.detectors import TextDetector
diff --git a/demo.py b/demo.py
index 026d961..f882ee0 100644
--- a/demo.py
+++ b/demo.py
@@ -8,10 +8,10 @@ from PIL import Image
 import model
 # ces
 
-paths = glob('./test/*.*')
+paths = glob('/home/zhoujianwen/CHINESE-OCR/test/*.*')
 
 if __name__ == '__main__':
-    im = Image.open("./test/3.png")
+    im = Image.open("/home/zhoujianwen/CHINESE-OCR/test/3.png")
     img = np.array(im.convert('RGB'))
     t = time.time()
     '''
diff --git a/ocr/model.py b/ocr/model.py
index 41c9459..c357809 100644
--- a/ocr/model.py
+++ b/ocr/model.py
@@ -72,7 +72,7 @@ def get_model(height, nclass):
 
 characters = keys_ocr.alphabet[:]
 modelPath = os.path.join(os.getcwd(), "ocr/ocr0.2.h5")
-# modelPath = '/Users/xiaofeng/Code/Github/dataset/CHINESE_OCR/save_model/my_model_keras.h5'
+ #modelPath = '/media/zhoujianwen/Data/dataset/crnn/my_model_keras.h5'
 height = 32
 nclass=len(characters)+1
 if os.path.exists(modelPath):
diff --git a/setup.sh b/setup.sh
index f75e990..cb921fd 100644
--- a/setup.sh
+++ b/setup.sh
@@ -1,8 +1,8 @@
 # conda create -n chinese-ocr python=2.7 pip scipy numpy PIL jupyter##运用conda 创建python环境
 # source activate chinese-ocr
 
-export PATH=/usr/local/cuda-9.0/bin${PATH:+:${PATH}}
-export LD_LIBRARY_PATH=/usr/local/cuda-9.0/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
+#export PATH=/usr/local/cuda-9.0/bin${PATH:+:${PATH}}
+#export LD_LIBRARY_PATH=/usr/local/cuda-9.0/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
 
 pip install easydict -i https://pypi.tuna.tsinghua.edu.cn/simple/ ##选择国内源，速度更快
 pip install keras==2.0.8  -i https://pypi.tuna.tsinghua.edu.cn/simple/  
@@ -13,7 +13,7 @@ pip install  h5py lmdb mahotas -i https://pypi.tuna.tsinghua.edu.cn/simple/
 conda install pytorch=0.1.12 cuda90 torchvision -c soumith
 pip install futures==3.1.1 -i https://pypi.tuna.tsinghua.edu.cn/simple/
 # conda install tensorflow=1.3 tensorflow-gpu=1.3 ##解决cuda报错相关问题
-cd ./ctpn/lib/utils
-sh make.sh
+#cd ./ctpn/lib/utils
+#sh make.sh
 
 
diff --git a/train/keras-train/allinonetrain.py b/train/keras-train/allinonetrain.py
index cb5db70..2dc0808 100644
--- a/train/keras-train/allinonetrain.py
+++ b/train/keras-train/allinonetrain.py
@@ -268,8 +268,8 @@ if __name__ == '__main__':
     model, basemodel = get_model(height=imgH, nclass=nclass)
     import os
 
-    if os.path.exists('/Users/xiaofeng/Code/Github/dataset/CHINESE_OCR/crnn_ocr/pretrain-models/keras.hdf5'):
-        basemodel.load_weights('/Users/xiaofeng/Code/Github/dataset/CHINESE_OCR/crnn_ocr/pretrain-models/keras.hdf5')
+    if os.path.exists('/home/zhoujianwen/CHINESE_OCR/crnn_ocr/pretrain-models/keras.hdf5'):
+        basemodel.load_weights('/home/zhoujianwen/CHINESE_OCR/crnn_ocr/pretrain-models/keras.hdf5')
 
     ##注意此处保存的是model的权重
     checkpointer = ModelCheckpoint(filepath="save_model/model{epoch:02d}-{val_loss:.4f}.hdf5", monitor='val_loss',
diff --git a/train/keras-train/train.py b/train/keras-train/train.py
index 9240f46..fba6f77 100644
--- a/train/keras-train/train.py
+++ b/train/keras-train/train.py
@@ -90,16 +90,16 @@ if __name__ == '__main__':
     import os
 
     if os.path.exists(
-            '/Users/xiaofeng/Code/Github/dataset/CHINESE_OCR/save_model/my_model_keras.h5'
+            '/media/zhoujianwen/Data/dataset/crnn/my_model_keras.h5'
     ):
         basemodel.load_weights(
-            '/Users/xiaofeng/Code/Github/dataset/CHINESE_OCR/save_model/my_model_keras.h5'
+            '/media/zhoujianwen/Data/dataset/crnn/my_model_keras.h5'
         )
 
     ##注意此处保存的是model的权重
     checkpointer = ModelCheckpoint(
         filepath=
-        "/Users/xiaofeng/Code/Github/dataset/CHINESE_OCR/save_model/my_model_keras.h5",
+        "/media/zhoujianwen/Data/dataset/crnn/my_model_keras.h5",
         monitor='val_loss',
         verbose=0,
         save_weights_only=False,
diff --git a/train/keras-train/trainbatch.py b/train/keras-train/trainbatch.py
index 9680bfd..39d19a4 100644
--- a/train/keras-train/trainbatch.py
+++ b/train/keras-train/trainbatch.py
@@ -20,7 +20,7 @@ nclass = len(characters) + 1
 trainroot = '../data/lmdb/train'
 valroot = '../data/lmdb/val'
 # modelPath = '../pretrain-models/keras.hdf5'
-modelPath = '/Users/xiaofeng/Code/Github/dataset/CHINESE_OCR/save_model/my_model_keras.h5'
+modelPath = '/media/zhoujianwen/Data/dataset/crnn/my_model_keras.h5'
 workers = 4
 imgH = 32
 imgW = 256
@@ -35,7 +35,7 @@ LEARNING_RATE = 0.01
 Learning_decay_step = 20000
 PERCEPTION = 0.3
 EPOCH_NUMS = 1000000
-MODEL_PATH = '/Users/xiaofeng/Code/Github/dataset/CHINESE_OCR/save_model'
+MODEL_PATH = '/media/zhoujianwen/Data/dataset/crnn'
 LOG_FILE = 'log.txt'
 SUMMARY_PATH = './log/'
 if not os.path.exists(MODEL_PATH):
diff --git a/train/pytorch-train/crnn_main.py b/train/pytorch-train/crnn_main.py
index 4083326..6a9cff0 100644
--- a/train/pytorch-train/crnn_main.py
+++ b/train/pytorch-train/crnn_main.py
@@ -58,8 +58,7 @@ parser.add_argument(
 parser.add_argument(
     '--crnn',
     help="path to crnn (to continue training)",
-    default=
-    '/Users/xiaofeng/Code/Github/dataset/CHINESE_OCR/save_model/netCRNN.pth'
+    default='/media/zhoujianwen/Data/dataset/crnn/netCRNN_pytorch.pth'
 )
 # parser.add_argument('--crnn', help="path to crnn (to continue training)",default='')
 parser.add_argument('--alphabet', default=alphabet)
```

**Comment by yuansaijie0604** [comment]
那个model.py出错，找到对应行看下，发现路径写的文件不存在，在google里搜那个文件
https://github.com/jiangxiluning/chinese-ocr/blob/master/ocr/ocr0.2.h5   你可以在这里下载，放到对应的位置
