### ISSUE TITLE
ModuleNotFoundError: No module named 'utils'

### ISSUE THREAD

**Issue by Nicolasdeke** [xiaofengShi/CHINESE-OCR#95]
请问一下这个是什么问题
Using TensorFlow backend.
Traceback (most recent call last):
  File "demo.py", line 8, in <module>
    import model
  File "D:\QQ\CHINESE-OCR-master (2)\CHINESE-OCR-master\model.py", line 13, in <module>
    from crnn.crnn import crnnOcr
  File "D:\QQ\CHINESE-OCR-master (2)\CHINESE-OCR-master\crnn\crnn.py", line 11, in <module>
    import models.crnn as crnn
  File "./crnn\models\crnn.py", line 4, in <module>
    import utils
ModuleNotFoundError: No module named 'utils'

**Comment by ghost** [comment]
打开./crnn\models\crnn.py文件，import sys下一句改为sys.path.insert(1, "./crnn/models")

**Comment by vance-coder** [comment]
crnn/models/crnn.py文件，将第4行改成： from . import utils
